### PR TITLE
feat: RM NEXT_PUBLIC use @next/bundle-analyzer for .env 

### PR DESCRIPTION
**Pull request by hirockstar**
add [demo.env](https://github.com/iRedScarf/onedrive-vercel-index/compare/main...therockstarind:RM_NEXT_PUBLIC?expand=1#diff-4e0ffb9c1cd1f8caf17e459773c005b24561f528df1e70e3394aac630e2c5541) to run on localhost

### CODE REVIEW

**Comment by iRedScarf** [comment]
I tested your code, when the OAuth authentication reaches the Step-3, there will be `Don't pretend to be the site owner` error message.

**Comment by hirockstar** [comment]
Okay I will check about that let's see if I found a solution for that.

**Comment by iRedScarf** [comment]
I have tried to set environment variables with non-NEXT_PUBLIC_ prefixes through API routing, but also in the Step-3 of OAuth authentication.

**Comment by hirockstar** [comment]
no worries will check there is nothing impossible.

**Comment by hirockstar** [comment]
provide client id and client secret I will test on my local what's causing this problem.

**Comment by iRedScarf** [comment]
Only clientId and clientSecret cannot perform complete OAuth authentication, so I suggest that you can register an E5 developer account with your own Microsoft account, you can get 25 sub-accounts, and each account can have 5T of OneDrive space, and you can also use Genuine desktop version of Microsoft 365 (Microsoft Office).

**Comment by hirockstar** [comment]
this can help you to fix that problem 
```
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { useTranslation, Trans } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import siteConfig from '../../config/site.config'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'

import { getAuthPersonInfo, requestTokenWithAuthCode, sendTokenToServer } from '../../utils/oAuthHandler'
import { LoadingIcon } from '../../components/Loading'
import { getAccessToken, getPrincipals } from '../../utils/odAuthTokenStore'

import { Player } from '@lottiefiles/react-lottie-player'
import { Step3 } from '../../utils/LottieUrl'

export default function OAuthStep3({ 
  accessToken, expiryTime, refreshToken, error, 
  description, errorUri, principals, token }) {
  
  const router = useRouter()
  const [expiryTimeLeft, setExpiryTimeLeft] = useState(expiryTime)
  const [accountAlreadyConnected, setAlreadyConnected] = useState(false)
  const [authPersonInfo, setAuthPersonInfo] = useState({ data: { userPrincipalName: '' }, status: -1 })

  getAuthPersonInfo(accessToken)
  .then(({data, status}) => {
    setAuthPersonInfo({data, status});
    if(Object.values(principals).includes(data.userPrincipalName)){
      setAlreadyConnected(true);
      setExpiryTimeLeft(0)
    }
  });

  const { t } = useTranslation()

  useEffect(() => {
    if (!expiryTimeLeft) return

    const intervalId = setInterval(() => {
      setExpiryTimeLeft(expiryTimeLeft - 1)
    }, 1000)

    return () => clearInterval(intervalId)
  }, [expiryTimeLeft])

  const [buttonContent, setButtonContent] = useState(
    <div>
      <span>{t('Store tokens')}</span> <FontAwesomeIcon icon="key" />
    </div>
  )
  const [buttonError, setButtonError] = useState(false)

  const sendAuthTokensToServer = async () => {
    setButtonError(false)
    setButtonContent(
      <div>
        <span>{t('Storing tokens')}</span> <LoadingIcon className="ml-1 inline h-4 w-4 animate-spin" />
      </div>
    )

    // verify identity of the authenticated user with the Microsoft Graph API
    const { data, status } = authPersonInfo;
    if (status !== 200) {
      setButtonError(true)
      setButtonContent(
        <div>
          <span>{t('Error validating identify, restart')}</span> <FontAwesomeIcon icon="exclamation-circle" />
        </div>
      )
      return
    }
    
    const principalNames = siteConfig.userPrincipalName.split(',').map(name => name.trim());
    const principalName = data.userPrincipalName.trim();

    if (principalNames.indexOf(principalName) < 0) {
      setButtonError(true)
      setButtonContent(
        <div>
          <span>{t('Do not pretend to be the site owner')}</span> <FontAwesomeIcon icon="exclamation-circle" />
        </div>
      )
      return
    }

    await sendTokenToServer(accessToken, refreshToken, expiryTime, principalName)
      .then(() => {
        setButtonError(false)
        setButtonContent(
          <div>
            <span>{t('Stored! Going home...')}</span> <FontAwesomeIcon icon="check" />
          </div>
        )
        setTimeout(() => {
          //window.location.href = '/#new-drive';
          window.location.href = '/';
        }, 3000)
      })
      .catch(_ => {
        setButtonError(true)
        setButtonContent(
          <div>
            <span>{t('Error storing the token')}</span> <FontAwesomeIcon icon="exclamation-circle" />
          </div>
        )
      })
  }

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-black">
      <Head>
        <title>{t('OAuth Step 3 - {{title}}', { title: siteConfig.title })}</title>
      </Head>

      <main className="flex w-full flex-1 flex-col bg-white dark:bg-black">
        <Navbar />

        <div className="mx-auto w-full max-w-5xl p-4">
          <div className="rounded-lg bg-white p-3 dark:bg-black dark:text-gray-100">
            <div className="mx-auto w-52">
            <Player autoplay loop src={Step3} style={{ height: '200px'}} ></Player>
            </div>
            <h3 className="mb-4 text-center text-xl font-medium">
              {t('Welcome to your new RDRIVE 🎉')}
            </h3>

            <h3 className="mt-4 mb-2 text-lg font-medium">{t('Step 3/3: Get access and refresh tokens')}</h3>
            {error || accountAlreadyConnected ? (
              <div>
                <p className="py-1 font-medium text-red-500">
                  <FontAwesomeIcon icon="exclamation-circle" className="mr-2" />
                  <span>
                    {accountAlreadyConnected ? t("This OneDrive account is already connected") : t('Whoops, looks like we got a problem: {{error}}.', {
                      // t('No auth code present')
                      error: t(error),
                    })}
                  </span>
                </p>
                <p className="my-2 whitespace-pre-line rounded-lg border border-gray-400/20 bg-gray-50 p-2 font-mono text-sm opacity-80 dark:bg-black">
                  {
                    // t('Where is the auth code? Did you follow step 2 you silly donut?')
                    accountAlreadyConnected ? authPersonInfo.data.userPrincipalName : t(description)
                  }
                </p>
                {errorUri && (
                  <p>
                    <Trans>
                      Check out{' '}
                      <a
                        href={errorUri}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline dark:text-blue-500"
                      >
                        {/* eslint-disable-next-line react/no-unescaped-entities */}
                        Microsoft's official explanation
                      </a>{' '}
                      on the error message.
                    </Trans>
                  </p>
                )}
                <div className="mb-2 mt-6 text-right">
                  <button
                    className="rounded-lg bg-gradient-to-br from-red-500 to-orange-400 px-4 py-2.5 text-center text-sm font-medium text-white hover:bg-gradient-to-bl focus:ring-4 focus:ring-red-200 disabled:cursor-not-allowed disabled:grayscale dark:focus:ring-red-800"
                    onClick={() => {
                      router.push('/add-drive/step-1')
                    }}
                  >
                    <FontAwesomeIcon icon="arrow-left" /> <span>{t('Restart')}</span>
                  </button>
                </div>
              </div>
            ) : (
              <div>
                <p className="py-1 font-medium">{t('Success! The API returned what we needed.')}</p>
                <ol className="py-1">
                  {accessToken && (
                    <li>
                      <FontAwesomeIcon icon={['far', 'check-circle']} className="text-green-500" />{' '}
                      <span>
                        {t('Acquired access_token: ')}
                        <code className="font-mono text-sm opacity-80">{`${accessToken.substring(0, 60)}...`}</code>
                      </span>
                    </li>
                  )}
                  {refreshToken && (
                    <li>
                      <FontAwesomeIcon icon={['far', 'check-circle']} className="text-green-500" />{' '}
                      <span>
                        {t('Acquired refresh_token: ')}
                        <code className="font-mono text-sm opacity-80">{`${refreshToken.substring(0, 60)}...`}</code>
                      </span>
                    </li>
                  )}
                </ol>

                <p className="py-1 text-sm font-medium text-teal-500">
                  <FontAwesomeIcon icon="exclamation-circle" className="mr-1" />{' '}
                  {t('These tokens may take a few seconds to populate after you click the button below. ') +
                    t('If you go back home and still see the welcome page telling you to re-authenticate, ') +
                    t('revisit home and do a hard refresh.')}
                </p>
                <p className="py-1">
                  {t(
                    'Final step, click the button below to store these tokens persistently before they expire after {{minutes}} minutes {{seconds}} seconds. ',
                    {
                      minutes: Math.floor(expiryTimeLeft / 60),
                      seconds: expiryTimeLeft - Math.floor(expiryTimeLeft / 60) * 60,
                    }
                  ) +
                    t(
                      "Don't worry, after storing them, RDRIVE will take care of token refreshes and updates after your site goes live."
                    )}
                </p>

                <div className="mb-2 mt-6 text-right">
                  <button
                    className={`rounded-lg bg-gradient-to-br px-4 py-2.5 text-center text-sm font-medium text-white hover:bg-gradient-to-bl focus:ring-4 ${
                      buttonError
                        ? 'from-red-500 to-orange-400 focus:ring-red-200 dark:focus:ring-red-800'
                        : 'from-green-500 to-teal-300 focus:ring-green-200 dark:focus:ring-green-800'
                    }`}
                    onClick={sendAuthTokensToServer}
                  >
                    {buttonContent}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      <Footer token={token}/>
    </div>
  )
}

export async function getServerSideProps({ query, locale }) {
  const { authCode } = query

  // Return if no auth code is present
  const accessToken = await getAccessToken(0);
  if (accessToken) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  if (!authCode) {
    return {
      props: {
        error: 'No auth code present',
        description: 'Where is the auth code? Did you follow step 2 you silly donut?',
        ...(await serverSideTranslations(locale, ['common'])),
      },
    }
  }

  const response = await requestTokenWithAuthCode(authCode)

  // If error response, return invalid
  if ('error' in response) {
    return {
      props: {
        error: response.error,
        description: response.errorDescription,
        errorUri: response.errorUri,
        ...(await serverSideTranslations(locale, ['common'])),
      },
    }
  }

  const { expiryTime, refreshToken } = response
  

  return {
    props: {
      error: null,
      expiryTime,
      accessToken,
      refreshToken,
      ...(await serverSideTranslations(locale, ['common'])),
      principals: await getPrincipals()
    },
  }
}
```

**Pull request closed without merging**
